### ISSUE TITLE
Release checklist

### ISSUE THREAD

**Issue by laurentS** [mapswipe/mapswipe#546]
This issue is a draft for a checklist to be used before doing a release of the app, and also includes some thoughts on templates for PRs to help with that process.

## Things to do for a (production) release
(These are in no particular order)
- [ ] Merge all translation PRs
- [ ] Check all security alerts and either close or merge them
- [ ] Verify outdated dependencies (with `yarn outdated`) and upgrade them
- [ ] Update fastlane
- [ ] Update cocoapods
- [ ] Check CI logs for the previous release (particularly around the playstore/appstore uploads from fastlane) for warnings about upcoming requirements
- [ ] 
## PR template

These points are meant to help with the above checklist.
- [ ] The CI checks are passing before merging the PR
- [ ] I've rebased my branch off a recent `dev` branch commit, or merged `dev` into my branch and resolved all conflicts
- [ ] I've commented my code enough to be understandable by another developer
- [ ] I have referenced related issues in the PR description

**Comment by Hagellach37** [comment]
* draft release notes

**Comment by Hagellach37** [comment]
* check that all translations are included in `src/shared/18n.js` and `src/shared/constant.js`

**Comment by laurentS** [comment]
- reassign items that can't get done for this release to the next release milestone

**Comment by laurentS** [comment]
- close PRs we don't need anymore
