### ISSUE TITLE
Send client type (mobile/web) along with results

### ISSUE THREAD

**Issue by ofr1tz** [mapswipe/mapswipe#852]
MapSwipe mobile apps [send the app version along with results](https://github.com/mapswipe/mapswipe/commit/9637a092a9dce2c07ecd0f6d3275839c5bbda5c3) to Firebase, while the [web app](https://github.com/mapswipe/mapswipe-web) currently does not. This will need to change, if only for the reason that Firebase functions currently reject results from Validate projects with custom options that do not contain a non-empty appVersion entry (https://github.com/mapswipe/mapswipe-web/issues/18).

If both the mobile app and the web app write an app version to the results, we will need a way to indicate whether the version number refers to the mobile or the web client.

Furthermore, indicating the client type would enable us to track the proportion of contributions made by the different clients in general and to specific projects, and to analyse potential differences in the outcome (mapping speed, quality, project type preferences, etc.)

This could be achieved by:
* adding an appropriate suffix to appVersion, or
* writing the client type separately to the results

```[tasklist]
### Tasks
- [ ] https://github.com/mapswipe/mapswipe-web/issues/52
- [ ] https://github.com/mapswipe/mapswipe/issues/881
- [ ] https://github.com/mapswipe/mapswipe/issues/882
```

**Comment by danbjoseph** [comment]
Thanks for documenting this @ofr1tz. 
@jc39963 and @Katbaloo can add this to a future maintenance prioritization conversation with Togglecorp.

**Comment by Katbaloo** [comment]
Have added this to our [Support & Maintenance](https://github.com/orgs/mapswipe/projects/13/views/1) board.

**Comment by kopitek8** [comment]
@ofr1tz 

The AppVersion is used to validate mobile app version support to prevent outdated, unsupported apps from pushing data to Firebase. For tracking client usage, we can add the `client_type` attribute in Firebase with values `web` or `mobile`. If `client_type` is `web`, we can also ignore AppVersion and its validation. We will have to store the `client_type` data in `mapping_sessions` table in the backend [here](https://github.com/mapswipe/python-mapswipe-workers/blob/dev/postgres/initdb.sql#L170-L183). 

How does this sound? If we agree to this approach, we will move ahead and create a document that summarizes the behavior and the requirement for this.

Looping in @laurentS @Hagellach37 @danbjoseph

**Comment by ofr1tz** [comment]
Thanks, sounds good to me in general.

For `appVersion`, I understand that you propose to change the respective Firebase function to ignore `appVersion` if the client type is web. I am wondering, however, if the web client should write its version to results anyway, as we might need that information at some point. Would that be an option or might it cause some issues somewhere?

For consistency, I'd propose to add the attribute in camel case as `clientType`  to Firebase.

Furthermore, I was wondering whether we can make the python stats worker write client type to the results csv to facilitate analysis?

**Comment by laurentS** [comment]
Hey all,

A couple of questions I think are worth keeping in mind when designing this:
- what is the behaviour for outdated apps when they can't push results? Is there a way to tell users to upgrade? I'm thinking of the worst case which would be where these people do a swiping session, then just keep getting confusing errors, and abandon the app in frustration.
- what is the impact on storage size and firebase traffic? If my memory is correct, the `mapping_sessions` table was by far the biggest one in the db, adding extra text columns to it could result in a substantial volume increase. Have you estimated by how much in the various scenarii? Same question for firebase uploads. (I doubt either of those is a deal breaker money-wise, but better check before than be sad afterwards :slightly_smiling_face:)

**Comment by tnagorra** [comment]
We can use [In-app updates](https://developer.android.com/guide/playcore/in-app-updates) feature for Android. The feature is available for devices running on Android 5.0 (API level 21)

**Comment by kopitek8** [comment]
@ofr1tz

Yes, we will make the necessary adjustments in the Firebase function to cater to mobile and web version. Let's go with the `clientType` property with possible values of 'web' and 'mobile'. Additionally, you can proceed in sending web version as you mentioned. It might be helpful down the line. 

---

@laurentS 

For question 1, we can use [In-app updates](https://developer.android.com/guide/playcore/in-app-updates) feature for Android. The feature is available for devices running on Android 5.0 (API level 21). We could not use this feature for previous releases as we were not on API level 21 yet. So, we added a condition in firebase to reject contributions for older app for projectType 2 when customOptions is defined. For the future releases, we can use "In-app updates" feature to notify users to update the application. We did not find a similar feature for IOS but we can also look into [App Uprade](https://appupgrade.dev/) library. 

As for question 2, We can add these metadata on the group element instead of result element. The costs should be minimal for Firebase uploads.

**Comment by ofr1tz** [comment]
The dev web app now sends appVersion and clientType with results to Firebase. This will be deployed to the prod web app very soon with the next release. Here's an example:

```json
{
  "0625DucpnGd7564FqE9ptTY0AYJ2": {
    "appVersion": "0.1.7",
    "clientType": "web",
    "endTime": "2024-10-08T14:43:23.284Z",
    "results": { ... },
    "startTime": "2024-10-08T14:41:34.707Z"
  }
}
```

This means that Firebase will now accept contributions to Validate projects with custom options from the web app.

What would be the next steps to make client type information available for further analysis?

I understand that we would need to store client_type in the mapping_sessions table. I am also wondering if it would be an option to add a client type column to the results csv created by the stats workers?

**Comment by kopitek8** [comment]
@ofr1tz Shall we close this issue as well?

**Comment by ofr1tz** [comment]
Regarding my last question: Do you think we could write the client type to the mapping sessions table and let the stats worker add client type to the results csv? This would allow us to analyse different app uses.

**Comment by kopitek8** [comment]
Yes, we're planning to work on it, @ofr1tz.

**Comment by kopitek8** [comment]
```[tasklist]
### Tasks
- [ ] Add client type in web
- [ ] Add client type in mobile
- [ ] Store client type in the database
```
