### ISSUE TITLE
Release plan towards Mapswipe 2.0

### ISSUE THREAD

**Issue by laurentS** [mapswipe/mapswipe#87]
Following our last call, and a chat with @Hagellach37, here are a few thoughts about releasing the app to the public in a more gradual way than we initially thought.

The challenge lies transitioning from the old backend data structure to the new one, as we cannot modify the old apps already out there.

## Key principles
- we keep all data in the same firebase instance all along
- we do not modify the old version of the backend scripts until we shut them down

## Proposed plan
- [x] we modify the new app and backend code to move all new data under a specific key/set of keys, eg: `/v2/projects`, `v2/groups`... (or `projects_v2`, `groups_v2`...) so there is no mix of old and new data structures (this includes user profiles, but NOT authentication, so no need for users to recreate an account)
- [x] import one or 2 new projects (of `BuiltArea` type, the original one) that only new app users will see. We keep the existing projects running for now, with all their existing setup (app, data, backend scripts, firebase and postgresql)
- [x] we setup the new backend scripts to transfer results from firebase_v2 to postgresql_v2 (so we have 2 separate databases, old & new, in postgresql)
- [x] we release the new app to a limited number of users via app/playstore (say about 50-100 users)
- [x] we stop importing projects in the old format, so that there are fewer and fewer of them available to old app users
- [x] when a user first logs in with the new app, we run some code to convert their stats to the new format (not sure how we do this yet)
- [x] we get bug reports, fix them, release updates, maybe increase the number of people who can get them as we go (I expect more users means more varied phones/OSes ==> more bugs)
- [x] once we're happy with the stability of the app, we release it to everyone, and put an announcement (in the old app) that we're retiring the old one, please update. At this point, there is pretty much no project left in the old format. Maybe we lose a few sqkm of area that is not completely mapped (but we could always recreate a new project for those bit)
- [x] we stop the old backend scripts, and then run a script to transfer old postgresql data to the new format. This can happen at any time once we know we won't receive any more results in the old format.
- [x] we celebrate! :champagne: :tada: 

## Prerequisites

- [x] Apple app store configuration is ready (both in our deployment code, and on the store config side) (#44)
- [x] Google playstore setup is ready (#43)
- [x] GDPR requirements are integrated in the app, or at least there's a clear plan (#77, ...)
- [x] No critical bugs (crashes, data corruption) occur when testing the currently available features on both iOS and Android

## Benefits of this approach

The key benefit of a progressive rollout to users is that we limit the number of people affected by bugs, but we actually see them happening, so we can fix them.

Old and new data are completely isolated, with the exception of user profiles which we update upon their first login via some script to be written.
After the transition, we keep the new data under the same `v2` location in firebase, until we feel a need for a `v3` :) So no risk of the old and new apps working together on shared data.

## Open questions

- how do we convert user profile data to the new format (progress stats...)
- are there any other points we've missed?

**Comment by laurentS** [comment]
I am going to close this, as we're past deployment of 2.0 by now.
